// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzimawxsbrmtoirmszxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6aW1hd3hzYnJtdG9pcm1zenhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MzE4MjAsImV4cCI6MjA2MTAwNzgyMH0.f6_sBEWIwchvjoiaLQ7KrUka3AdiWxcOf0QdIGHFiBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);